kind: pipeline
type: docker
name: crowdstrike

steps:
- name: pylint
  image: python:3.8
  commands:
  - pip install --quiet pipenv
  - pipenv install --dev
  # W0511 = TODO
  - pipenv run pylint --disable=W0511 crowdstrike 
- name: test1
  image: python:3.8
  commands:
  - pip install --quiet pipenv
  - pipenv install --dev
  - pipenv run pytest
  environment:
    CLIENT_ID:
      from_secret: CLIENT_ID
    CLIENT_SECRET:
      from_secret: CLIENT_SECRET